version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: myStrongP@ssw0rd
      MYSQL_DATABASE: simple_eshop
    ports:
      - 3306:3306
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
    volumes:
      - mysql-data:/var/lib/mysql/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: false

volumes:
  mysql-data:
    driver: local
  rabbit-data:
    driver: local
